services:
  quant_signals:
    container_name: quant_signals
    image: mayberry4477/quant_signals:latest
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgresql+psycopg://quant:quant_dev_password@postgres:5432/quant
      - QUANT_REDIS_URL=redis://quant_redis.quant.mayberry.farm:6379/0
      - API_PORT=8016
      - MAINTENANCE_INTERVAL=60
    ports:
      - "8016:8016"
